### ISSUE TITLE
Add App UI Translations: Turkish & French, Persian

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#113]
- [x] Turkish
- [x] French
- [x] Persian

**Comment by Dianaaiym** [comment]
added french lang: https://crowdin.com/project/bank-wallet/fr#

**Comment by Dianaaiym** [comment]
added persian lang: https://crowdin.com/project/bank-wallet/fa#

**Comment by Dianaaiym** [comment]
added turkish lang:
