### ISSUE TITLE
Add coin exchange rate in coin holder cell

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-ios#122]
<img width="514" alt="screen shot 2018-10-25 at 3 28 39 pm" src="https://user-images.githubusercontent.com/42367908/47490509-af101580-d86a-11e8-9d7a-9a7402795da2.png">

zpl://screen?sid=5b8fb90c659cd9af82503ec2&pid=5b167c731d079e4122e946b7

**Comment by esengulov** [comment]
I see that exchange rates been already implemented. closing the issue
