### ISSUE TITLE
Design Coin Manager

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-ios#132]
- [ ] "+" button on home tab
- [ ]   "Add Coins" screen. 
-- the activated coins sorted by the order specified by user
-- unactivated coins sorted alphabetically (based on token's name, not symbol)

**Comment by esengulov** [comment]
@TalgatNurdinov once controllers are ready upload them here.

@Dianaaiym Localize text strings and list them here along with the design mockups as a reference for @mNizhurin

**Comment by TalgatNurdinov** [comment]
<img width="765" alt="screen shot 2018-11-16 at 6 17 54 pm" src="https://user-images.githubusercontent.com/42367908/48620918-0158d800-e9cc-11e8-95c8-b4e0a0061755.png">

**Comment by esengulov** [comment]
@Dianaaiym design is ready, create new localizable strings based on the above design

**Comment by Dianaaiym** [comment]
Added new localizable strings
@mNizhurin
"settings.manage_wallet"
"settings_manage_wallet.title" 
"settings_manage_wallet.add_coins"
"settings_manage_wallet.add_button" 
"settings_manage_wallet.hide_button"
"settings_manage_wallet.remove_button" 
"settings_manage_wallet.show_button" 
"settings_manage_wallet.search_placeholder"

**Comment by ealymbaev** [comment]
@esengulov @TalgatNurdinov what is the difference between "Show / Hide" and "Add / Remove"???
Technically it seems to be the same action.

**Comment by esengulov** [comment]
@TalgatNurdinov requesting minor changes:

- [ ]  Add "+" button below the coins on BALANCE tab
- [ ] click on the "+" should open the add coins controller that lists all available coins (with add/remove button). The controller should have DONE button at the top.

**Comment by TalgatNurdinov** [comment]
<img width="512" alt="screen shot 2018-12-14 at 5 57 05 pm" src="https://user-images.githubusercontent.com/42367908/50002286-d7460600-ffc9-11e8-9239-8572fde72296.png">

https://zpl.io/VOKopMY

**Comment by esengulov** [comment]
@TalgatNurdinov at this point let's remove the order arrangement options. It's not critical at this point

**Comment by esengulov** [comment]
@TalgatNurdinov please provide light mode version as well!

When ready add the light version here under Wallet 1.1 project (https://github.com/horizontalsystems/bank-wallet-ios/projects)

**Comment by TalgatNurdinov** [comment]
<img width="509" alt="screen shot 2018-12-19 at 4 59 17 pm" src="https://user-images.githubusercontent.com/42367908/50216238-70509480-03af-11e9-8bb7-be8ee17fb9c9.png">

**Comment by TalgatNurdinov** [comment]
> @TalgatNurdinov please provide light mode version as well!

<img width="244" alt="screen shot 2018-12-19 at 5 02 27 pm" src="https://user-images.githubusercontent.com/42367908/50216418-e654fb80-03af-11e9-8570-4349609895e9.png">

**Comment by esengulov** [comment]
@TalgatNurdinov looks good!
