### ISSUE TITLE
Update layout on Welcome screen

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#136]
- [x] design completed, see below. if there are any question direct them to @TalgatNurdinov 
- [x] the language. should be same to the language set on user's OS. if the language not available on bank wallet then display English.

**Comment by esengulov** [comment]
@TalgatNurdinov please upload confirmed screens

**Comment by TalgatNurdinov** [comment]
<img width="248" alt="screen shot 2018-12-12 at 2 43 07 pm" src="https://user-images.githubusercontent.com/42367908/49857235-4251da00-fe1c-11e8-83ce-f9ad02f287c2.png">

**Comment by esengulov** [comment]
@TalgatNurdinov let's move the version "version 1.1" below the buttons and make the BANK Wallet title standout a bit

**Comment by esengulov** [comment]
@TalgatNurdinov @mNizhurin the design for welcome screen is work in progress. Pleas redo not start working on the issue unless there is an update below this comment with an updated version of design.

**Comment by TalgatNurdinov** [comment]
![welcome_image 2x](https://user-images.githubusercontent.com/42367908/53469482-40490000-3a88-11e9-8e84-52df5de794d1.png)
![welcome_image 3x](https://user-images.githubusercontent.com/42367908/53469483-40490000-3a88-11e9-8c7c-022973ad968a.png)

https://zpl.io/2EjZg5e

**Comment by mNizhurin** [comment]
Label version has no word "version" before number.
