### ISSUE TITLE
Balance tab: syncing state

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-ios#138]
- [ ] Total Balance from old data should be transparent 50%
- [ ] If currency rate not available do not show anything
- [ ] If currency rate from old data should be transparent #grey 50%
- [ ] Remove the word "syncing" show only the percentages
- [ ] Deactivate send button on syncing

<img width="247" alt="screen shot 2018-11-26 at 5 14 44 pm" src="https://user-images.githubusercontent.com/42367908/49010971-06bddb80-f19f-11e8-9620-98c0f746c55e.png">

web - https://zpl.io/2EKRD5y
app - zpl://screen?sid=5bd7f9c37265930a07e00ecd&pid=5b167c731d079e4122e946b7

**Comment by esengulov** [comment]
@TalgatNurdinov removed " Outdated rate should be showed with timestamp". After testing this on Android we agreed that showing outdated ex rate with time stamp would take too much space
