### ISSUE TITLE
ERC 20 Token support

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#141]
- [x] after coin manager is ready
- [x] Use the ERC20.json file from IPFS (the copy of the file available in one of HS repositories), as a source for the erc20 icons and other token parameters. Refer to the note below.
- [x] sync with the source file once a day
- [x] when a coin is removed from the IPFS source file but that same coin is active for some users then the coin should be available to those users, until is disabled.
- [x] Support svg files for coin icons
- [x] when user tries to transfer ERC20 coin but there is not enough ETH balance to pay the fee an alert should be shown. @Dianaaiym will provide the key value for the localization string 
- [x] Show fee in ETH
- [x] Support rate for ETH fee

Note:  For each ERC20 contract there is:

- "coin symbol": "BNB",
- "coin name": "Binance Coin",
- "decimal count"
- "contract address": "0xB8c77482e45F1F44dE1745F52C74426C631bDD52"

Once the wallet knows the contract address it may get relevant icons for the coin from IPFS

ERC20 source file location:

https://ipfs.horizontalsystems.xyz/ipns/Qmd4Gv2YVPqs6dmSy1XEq7pQRSgLihqYKL2JjK7DMUFPVz/io-hs/data/blockchain/ETH/erc20

JSON file :
https://ipfs.horizontalsystems.xyz/ipns/Qmd4Gv2YVPqs6dmSy1XEq7pQRSgLihqYKL2JjK7DMUFPVz/io-hs/data/blockchain/ETH/erc20/index.json

**Comment by Dianaaiym** [comment]
Use this key for alert "send_erc.alert"
