### ISSUE TITLE
Initial open of Edit Pin screen takes quite long time

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/bank-wallet-ios#171]

**Comment by mNizhurin** [comment]
Problem is in navigation controller appearance settings. When setting barStyle or preferredStatusBarStyle, controller load takes random time to complete. Some times it freezes after did load another time after will appear.
I suppose to change design and get rid of navigation controller here.

logs:
tap edit pin
start open edit 0
controller created 0
did load 8862        !!!!!
will appear 6
did appear 561

tap edit pin
start open edit 0
controller created 0
did load 95
will appear 7
did appear 1366     !!!!!
