### ISSUE TITLE
Send controller: Paste button must be visible only when clipboard non empty

### ISSUE THREAD

**Issue by ant013** [horizontalsystems/bank-wallet-ios#186]

**Comment by ealymbaev** [comment]
iOS pasteboard is usually not empty, so this enhancement is not so important. Dropping it for now.

**Comment by esengulov** [comment]
> iOS pasteboard is usually not empty, so this enhancement is not so important. Dropping it for now.

agreed! this was simpler to get implemented on Android so it went through without much discussion. We'll see if there are any valid use cases for it based on the future feedback and if it becomes crucial we'll get implemented on iOS client s well
