### ISSUE TITLE
Transactions Tab: further UI Improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#188]
- [x] pending transactions should standout. The pending icon is not enough its it's hardly visible. Perhaps highlighting the background of such transaction would make them standout more. 
- [x] try reversing placements of crypto with base currency on transactions tab. 
- [x] consider adding "sending" text to all pending transactions (@Dianaaiym note "sending" text, should be localized)

**Comment by TalgatNurdinov** [comment]
<img width="511" alt="screen shot 2018-12-10 at 3 49 22 pm" src="https://user-images.githubusercontent.com/42367908/49724303-31299180-fc93-11e8-921a-a401d8658312.png">
https://zpl.io/adkQWlp

**Comment by esengulov** [comment]
@TalgatNurdinov looks good, accepted. If you haven't added this issue to Android repository then you need to add it there as well

**Comment by TalgatNurdinov** [comment]
![transactions](https://user-images.githubusercontent.com/42367908/50413521-f189aa80-0839-11e9-90f5-4df184cdc5a0.jpg)
