### ISSUE TITLE
Balance Tab: introduce failed/error state for blockchain sync job to coin cell

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#214]
We currently have  syncing and synced states.

We also need to have failed state for sync. When a coin fails to sync for some reason we should allow user to force retry.

@TalgatNurdinov: provide the design for such use case

**Comment by TalgatNurdinov** [comment]
<img width="250" alt="screen shot 2018-12-06 at 4 00 45 pm" src="https://user-images.githubusercontent.com/42367908/49576777-29ef4480-f970-11e8-8c98-ddec6ab0eb8a.png">

https://zpl.io/2EKRD5y
