### ISSUE TITLE
Tab bar animation issue

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#227]
Build 1.0.66
Go to Settings and then to process to one of the child menus (base currency or language). Swipe back and watch the tab bar.

It looks better on Back button click but still not the way it should be. The tab bar should slide together with the view controller.

**Comment by esengulov** [comment]
@mNizhurin thanks for the correction ;)

**Comment by mNizhurin** [comment]
ios 12.1 bug. Won't fix.

**Comment by esengulov** [comment]
@mNizhurin bug still exists on iOS 11.1.2
