### ISSUE TITLE
Dark / Light mode support for coin send/receive controllers

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#230]
We need dark/light mode support for the:

- [x] send. controller
- [x] receive controller
- tx info (collapsed/expanded states)

Present Situation: 

in both light and dark mode: All three controllers are light colored and appear on darkish background. In dark mode the controllers should be dark and the background layer should be light-colored so that there is contrast. For the light mode do the opposite, light color controllers on a darkish background.

**Comment by TalgatNurdinov** [comment]
<img width="1047" alt="screen shot 2018-12-10 at 4 08 36 pm" src="https://user-images.githubusercontent.com/42367908/49725437-df363b00-fc95-11e8-9d99-ed66881d6034.png">

https://app.zeplin.io/project/5b167c731d079e4122e946b7/dashboard?seid=5b8fb953fb8abf20386a616f

**Comment by esengulov** [comment]
@TalgatNurdinov looks good
