### ISSUE TITLE
Full transaction info design

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-ios#232]
<img width="774" alt="screen shot 2018-12-10 at 2 26 27 pm" src="https://user-images.githubusercontent.com/42367908/49719529-a000ed80-fc87-11e8-831f-fab19a44b97b.png">
<img width="773" alt="screen shot 2018-12-10 at 2 26 35 pm" src="https://user-images.githubusercontent.com/42367908/49719530-a0998400-fc87-11e8-88cb-7f67d4753d45.png">

https://app.zeplin.io/project/5b167c731d079e4122e946b7/dashboard?seid=5c0e22c28d3fd05f043eca53

**Comment by esengulov** [comment]
@TalgatNurdinov looks good, consider it completed!

**Comment by TalgatNurdinov** [comment]
<img width="778" alt="screen shot 2018-12-20 at 4 30 08 pm" src="https://user-images.githubusercontent.com/42367908/50279657-87a58580-0474-11e9-823e-138379a8b27a.png">

**Comment by esengulov** [comment]
@TalgatNurdinov update this page with the latest layout. Need two versions:

- [ ] BTC/BCH
- [ ] ETH

**Comment by TalgatNurdinov** [comment]
for ETH
<img width="383" alt="screen shot 2019-01-18 at 11 34 10 am" src="https://user-images.githubusercontent.com/42367908/51367482-0d206200-1b15-11e9-8d73-91bd2a87b9e0.png">

**Comment by TalgatNurdinov** [comment]
final design
<img width="513" alt="screen shot 2019-01-18 at 11 33 21 am" src="https://user-images.githubusercontent.com/42367908/51367501-1f9a9b80-1b15-11e9-9b56-53a3478c9104.png">

**Comment by esengulov** [comment]
also include the source selection controller @TalgatNurdinov

**Comment by TalgatNurdinov** [comment]
<img width="246" alt="screen shot 2019-01-18 at 12 09 44 pm" src="https://user-images.githubusercontent.com/42367908/51368512-f6303e80-1b19-11e9-80e0-237505084807.png">

https://zpl.io/VKKP04E

**Comment by esengulov** [comment]
thanks! @TalgatNurdinov
