### ISSUE TITLE
Implement Full Transaction Info

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#243]
- [x] apply light and dark mode
- [x] expanded/collapsed mode design
- [x] design/layout: https://github.com/horizontalsystems/bank-wallet-ios/issues/232
- [x] "Data Provider": should open data source selection controller (design attached below, on January 18'th). 
- [ ] if the given API provides the FEE(in fiat) only in USD, then show that for all currencies.
- [x] for Ethereum blockchain we want extra fields (Gas price, Gas used, Gas limit). These blockchain specific terms should be hardcoded, we will not localize them.

- [x] integrate the following APIs as the data providers for "blockchain explorers"
- [x] the Share button should be sharing the website link to that transaction on that public block explorer. 
-- if I am sharing with someone transaction than I am basically sending a link to that transaction on selected block explorer. 
-- test the feature with WhatsApp, Telegram and Facebook messenger. 

##Blockchain Explorers

BTC 
-http://btc.horizontalsystems.xyz (default) 
 -https://btc.com (https://btc.com/api-doc#General   (no access keys, supposedly no restrictions)
-https://blockexplorer.com/api-ref  (no access keys, supposedly no restrictions)
-https://blockchair.com  (no access keys, supposedly no restrictions)
-//IPFS(coming soon, do not add it now)

  BCH
-http://bch.horizontalsystems.xyz (default)
-https://blockchair.com  (no access keys, supposedly no restrictions)
-//IPFS(coming soon, do not add it now)

 ETH
-http://eth.horizontalsystems.xyz (default)
-https://blockchair.com  (no access keys, supposedly no restrictions)
-https://etherscan.io/apis   (the free key on this API restricted to 5 calls/second. As an option we can ask the user to obtain his own free key(https://etherscan.io/myapikey) and use it. That would require an additional step on our end where user will be asked to add the API Key.
-//IPFS(coming soon, do not add it now)

**Comment by Dianaaiym** [comment]
Added new localizable strings
"tx_info.button_more" 
"full_info.title"
"full_info.id"
"full_info.status"
"full_info.time"
"full_info.block"
"full_info.confirmations"
"full_info.total_input"
"full_info.total_output"
"full_info.fee"
"full_info.subtitle_from"
"full_info.subtitle_inputs"
"full_info.subtitle_outputs"
"full_info.subtitle_provider"

**Comment by esengulov** [comment]
@ant013 note the updated tasks list in description

**Comment by ant013** [comment]
Need additional translates.

full_info.no_address - not available (Bitcoin info with segwit address in blockchain, which can't parse bc1....)
full_info.sat_byte - sat/B
full_info.fee_rate - Fee Rate
full_info.bytes - bytes ( size in bytes )

//Ethereum

full_info.gas_limit - Gas Limit
full_info.gas_used - Gas Used
full_info.gas_price - Gas Price
full_info.nonce - Nonce
full_info.value - Value
full_info.from - From
full_info.to - To

//Error
full_info.error.subtitle - offline
full_info.error.retry - retry

**Comment by Dianaaiym** [comment]
@ant013 Added
// Full Info 
"full_info.no_address"
"full_info.sat_byte"
"full_info.fee_rate"
"full_info.bytes"

// Full Info Ethereum
"full_info_eth.gas_limit"
"full_info_eth.gas_used"
"full_info_eth.gas_price"
"full_info_eth.nonce"
"full_info_eth.value"
"full_info_eth.from"
"full_info_eth.to"

// Full Info Error
"full_info_error.subtitle"
"full_info_error.retry"

**Comment by Dianaaiym** [comment]
![2019-02-05 16 54 41](https://user-images.githubusercontent.com/22589457/52268881-c204ac80-2966-11e9-99cc-24dc1a5a028a.jpg)
Wrong color for Blockexpl link used, when switch themes
