### ISSUE TITLE
Transactions / Balance Tab: UI Changes

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#247]
- [x] Transactions tab: design: https://github.com/horizontalsystems/bank-wallet-ios/issues/188
- [x] Balance tab (see attached)
- [x] send confirmation controller minor change (design attached)

**Comment by esengulov** [comment]
- [ ] pending transactions should standout.
- [ ] reverse placements of crypto with base currency
- [ ] use "sending" text with filled/empty bar icons on all pending transactions to indicate transaction confirmation status

**Comment by TalgatNurdinov** [comment]
<img width="511" alt="screen shot 2018-12-19 at 6 42 26 pm" src="https://user-images.githubusercontent.com/42367908/50220930-d9d79f80-03bd-11e9-8df6-277942735ccb.png">

**Comment by TalgatNurdinov** [comment]
<img width="247" alt="screen shot 2018-12-19 at 6 43 21 pm" src="https://user-images.githubusercontent.com/42367908/50220988-fa075e80-03bd-11e9-8a22-dc8295decfac.png">

**Comment by esengulov** [comment]
on pending transactions: date and timestamp overlaps with pending icon and confirmation bars, respectively
