### ISSUE TITLE
Design Transaction fee Adjustment (Send Confirmation)

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#250]
I am thinking we should start with three values: low, normal, priority. it should appear in send confirmation controller.

At the same time should be compatible with various blockchains that may have zero or standard fee rates

**Comment by TalgatNurdinov** [comment]
![send filled custom numpad copy 4](https://user-images.githubusercontent.com/42367908/53565183-ebd67b00-3b82-11e9-9feb-085fd02c24ed.png)
https://zpl.io/aR1zxBE

**Comment by esengulov** [comment]
consider it done!
