### ISSUE TITLE
Receive Controller: UI Improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#294]
- [x] try adding "Your Address" somewhere so that it's clear to the user what that address string and QR code is for.

- [x] the title for controller: instead of using coin symbol in title use it's name. So, the title for Bitcoin receive controller should be "Receive Bitcoin", not "Receive BTC"

**Comment by TalgatNurdinov** [comment]
![receive](https://user-images.githubusercontent.com/42367908/50591182-5be4bf80-0eb8-11e9-9211-cb19862a1eec.png)

**Comment by TalgatNurdinov** [comment]
<img width="512" alt="screen shot 2019-01-04 at 12 02 23 pm" src="https://user-images.githubusercontent.com/42367908/50675481-9cf3e580-1018-11e9-86cc-511f9d8a138b.png">

**Comment by esengulov** [comment]
done!
