### ISSUE TITLE
Send Controller Improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#295]
Think about integrating following elements into send controller:

- [x] option to send entire balance
- [x] allow user to select one of the bookmarked payment addresses

**Comment by TalgatNurdinov** [comment]
![send filled custom numpad copy](https://user-images.githubusercontent.com/42367908/50625642-a109ff80-0f53-11e9-86f3-ced47d28f94a.png)
![send filled custom numpad](https://user-images.githubusercontent.com/42367908/50625643-a1a29600-0f53-11e9-8f1a-3fc1f91e824a.png)

**Comment by esengulov** [comment]
@TalgatNurdinov looks good, waiting for the "favorites/bookmarked" addresses selection button/menu

**Comment by TalgatNurdinov** [comment]
<img width="381" alt="screen shot 2019-01-04 at 12 18 16 pm" src="https://user-images.githubusercontent.com/42367908/50675849-d9284580-101a-11e9-8a5d-b764ced43115.png">

**Comment by esengulov** [comment]
consider it done!
