### ISSUE TITLE
In Light Mode: the initial background that's briefly shown on App Start should be light colored

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#304]
In the dark mode the initial background matches the background of the controllers in the app and as a result the app start process looks visually pleasing. 

On switch to the light mode, the background on start remains dark but the bg in app controllers changes and this results in not so elegant app start :) Needs fix!

**Comment by ealymbaev** [comment]
As long as I know iOS does not allow conditional Launch Screen (Launch Image).

**Comment by esengulov** [comment]
> As long as I know iOS does not allow conditional Launch Screen (Launch Image).

seems you're right, I checked a couple of apps that come with dark mode and it seems that Launch Screen remains same there as well.

Closing the issue!
