### ISSUE TITLE
Transaction Info Bottom Controller: Show Text "Pending" before icon

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-ios#313]
At the moment it's not clear to the user, what happens to the Transactions. It seems like a bug

design https://zpl.io/bAZmQ3P / or 
https://github.com/horizontalsystems/bank-wallet-ios/issues/316

**Comment by Dianaaiym** [comment]
![2019-01-14 11 47 10](https://user-images.githubusercontent.com/22589457/51097960-3332c300-17f2-11e9-9ce0-4e90814a760b.jpg)

**Comment by TalgatNurdinov** [comment]
https://zpl.io/bAZmQ3P
