### ISSUE TITLE
ERC 20 Tokens: Add Alert "Need ETH To Transfer Tokens"

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-ios#351]
When sending a token, you don't have enough funds on your ETH balance

Add Alert "You Need ETH To Transfer"

**Comment by ealymbaev** [comment]
@ant013 please describe how EthereumAdapter will report that user does not have enough ETH balance for transferring ERC20 coin.

**Comment by esengulov** [comment]
Issue Merged Into https://github.com/horizontalsystems/bank-wallet-ios/issues/141

**Comment by ant013** [comment]
When user try click on send erc20 button, we must check that user have ethereumKit balance more or equal erc20fee value
