### ISSUE TITLE
Settings: Nav bar Title is appear as Back Button

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-ios#383]
It's only in Spanish and French version
![img_0405](https://user-images.githubusercontent.com/22589457/51967957-e5c57f80-249a-11e9-9570-530fedfc8e08.PNG)

**Comment by ealymbaev** [comment]
We have decided to always show Back button with custom localized title

**Comment by ealymbaev** [comment]
Let's always show full title despite its length instead of default Back button
