### ISSUE TITLE
Sort coins in manager with defaults

### ISSUE THREAD

**Issue by ant013** [horizontalsystems/bank-wallet-ios#415]
If disable default coin in manager, go back and open manager again - default coin must sorted but stand at end

**Comment by esengulov** [comment]
@ant013 @mNizhurin 

in coin manager, the first 3 should always be:

- Bitcoin
- Etherem
- Bitcoin Cash

**Comment by ealymbaev** [comment]
In Manage Coins module default coins are duplicated

**Comment by ealymbaev** [comment]
This happened because of old testnet coins names. Closing the issue
