### ISSUE TITLE
send controller: validate inputs

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#46]
When user tries to send currency to someone the wallet should check that:

- [ ] a provided address is a valid currency (ex: Bitcoin) address. Same applies to all other currencies as well. If user tries to send BTC to an Ethereum address then a respective error "invalid address" should be shown below the input field. 
- [ ] display error below input field if the balance is insufficien
- [ ] Send button should remain inactive while there are input errors (amount, address)

@TalgatNurdinov please provide the design for the insufficient balance error message to @mNizhurin

@mNizhurin it should be noted that the balance should be calculated on a currency level. In other words, if I am trying to send BTC then we should ensure that there is enough BTC (not the total balance)

**Comment by TalgatNurdinov** [comment]
![send error](https://user-images.githubusercontent.com/42367908/45091816-63c46b00-b135-11e8-969e-7213adc297ae.png)

**Comment by esengulov** [comment]
merged with https://github.com/horizontalsystems/bank-wallet-ios/issues/52
