### ISSUE TITLE
Implement confirm transaction controller after send

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-ios#47]
This controller show after click on send, where you can see fees. (ignore priority cell)

zpl://screen?sid=5b8fb90ef82810abf8e13bc0&pid=5b167c731d079e4122e946b7 (app link)

<img width="246" alt="screen shot 2018-10-30 at 5 03 23 pm" src="https://user-images.githubusercontent.com/42367908/47713975-c6ce0c00-dc65-11e8-810a-4bfd95eed135.png">

**Comment by esengulov** [comment]
moved to https://github.com/horizontalsystems/bank-wallet-ios/issues/52
