### ISSUE TITLE
Issue with sending/receiving ETH and ERC20 Tokens

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-ios#474]
- [x] Send Controller: After the user clicks on send in "Send confirm", the balance should be changed
- [x] Receive: Unconfirmed transactions for ETH and ERC20, these transactions should observe they protocol for unconfirmed transactions. In other words the transaction affects balance only after it’s confirmed. In the same way not possible to use pending funds for new transactions.

**Comment by ant013** [comment]
While we using infura for get state and balance of wallet we can only change request for balance to calculating include pending transactions.
