### ISSUE TITLE
Full Transaction Info: Impossible to change Source(blockexplorer) to Etherscan.io

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-ios#475]
Relevant only to ERC20 Tokens

**Comment by ant013** [comment]
reason: 

func setBaseProvider(name: String, for coinCode: String) {
        if coinCode.range(of: "ETH") != nil {

remove using coinCode in FullTransactionProviderSettings to choose type. Use coinType

**Comment by mNizhurin** [comment]
Fixed in #483
