### ISSUE TITLE
Release app version 0.3

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/bank-wallet-ios#505]

**Comment by ealymbaev** [comment]
Uploaded build to iTunesConnect

**Comment by ealymbaev** [comment]
Issue will be closed when app is released on AppStore

**Comment by Dianaaiym** [comment]
Available on App Store 
https://itunes.apple.com/us/app/bank-bitcoin-wallet/id1447619907?ls=1&mt=8
