### ISSUE TITLE
change the font color of "description texts"

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#51]
change the font color of "description texts" on following pages to #grey:

- [x] wallet intro page
- [x] backup wallet, 
- [x] backup wallet -> paper keys page 
- [x] backup wallet -> submit keys page
- [x] pin pages

**Comment by ealymbaev** [comment]
e53e0f75285c3228898f48e853a1ef18de70f398
830c679309a9fb331bc1f185241291a1f3091623
e25eaf3d90cc3414f419ce5864b34f1dc6958544
