### ISSUE TITLE
Design Lightning Network for BTC

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#516]

**Comment by esengulov** [comment]
@TalgatNurdinov status

**Comment by TalgatNurdinov** [comment]
<img width="245" alt="Screen Shot 2019-03-13 at 2 13 50 PM" src="https://user-images.githubusercontent.com/42367908/54263112-3ea82d80-459a-11e9-9a2b-87a720c7344c.png">
https://zpl.io/aR19eAp
