### ISSUE TITLE
Add New ERC20 Tokens

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#525]
- [x] Aurora DAO
-- contract address: 0xcdcfc0f66c522fd086a1b725ea3c0eeb9f9e8814  

- [x] EnjinCoin
-- contract address: 0xf629cbd94d3791c9250152bd8dfbdf380e2a3b9c 

- [x] Wax
contract address:  0x39Bb259F66E1C59d5ABEF88375979b4D20D98022

- [x] IDXM
contract address: 0xcc13fc627effd6e35d2d2706ea3c4d7396c610ea

- [x] @TalgatNurdinov please attach icons for these coins (for iOS)

**Comment by TalgatNurdinov** [comment]
coin icons - https://zpl.io/br8P0XW
