### ISSUE TITLE
Restore/Create Wallet: Add new confirmation boxes

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-ios#528]
When restoring or creating wallet, we should be show user a bottom sheet dialog with 3 confirmation boxes. 

Use keys:
"backup.confirmation.secret_key" 
"backup.confirmation.delete_app_warn" 
"backup.confirmation.disclaimer"

**Comment by TalgatNurdinov** [comment]
https://zpl.io/2p46dlM
