### ISSUE TITLE
Settings ->Backup Wallet: After the unlock screen briefly seeing Backup Screen

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-ios#531]
Ideally: Settings -> Backup Wallet -> Unlock Screen ->  Backup Words

**Comment by mNizhurin** [comment]
It is supposed to be that way. Unlock controller is not related with backup controllers in any way except verifying. You can imagine unlock screen as alert view. @TalgatNurdinov ?
