### ISSUE TITLE
UI Refactoring list 

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-ios#532]
## Inputs
- Single Line
- Multi line
- [ ] Font Styles
- [ ] Buttons
- [ ] Icons
- [ ] Errors

https://zpl.io/2p4PP1M

## Cells 
- Single Line
-  Multi line
- [ ] Font Styles
- [ ] Icons
- [ ] Accessories
- [ ] Dividers

https://zpl.io/2p4PP1M

## Header / Footer 
- [ ] Light/Dark

## Nav Bars
- App Bar
- Tab / Amount / Hash bar
-  Botton bar
- [ ] Font Styles
- [ ] Icons
- [ ] Dividers

zpl.io/VqWnxj7

## Controllers
-  Confirm
-  Receive
- Send
-  Send Confirm
- [ ] Font Style
- [ ] Icons 
- [ ] New cells

https://zpl.io/aw4Pr8g

**Comment by mNizhurin** [comment]
Most is done. Left part separated to issue #563
