### ISSUE TITLE
Send Controller:  shouldn't be possible to enter amount in FIAT if rate is outdated

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#535]
Send Controller:  it shouldn't be possible to enter amount in FIAT if the rate on the client side is more than 10 min long.

Was able to reproduce the case when the client used the rate which was more than 8 hours old.

Work together with android team. It's not entirely clear that this bug is present on Android client so while making the fix make sure that the fix gets duplicated to Android client as well. There is a corresponding issues on Android repository, https://github.com/horizontalsystems/bank-wallet-android/issues/756

**Comment by mNizhurin** [comment]
Can't reproduce

**Comment by ealymbaev** [comment]
Issue is not resolved yet, still reproduces
