### ISSUE TITLE
Rename Wallet to Unstoppable

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#574]
- [x] change app name
- [x] apply new icon

**Comment by esengulov** [comment]
@TalgatNurdinov we need a new icon here

**Comment by TalgatNurdinov** [comment]
[unstoppable_appicons.zip](https://github.com/horizontalsystems/bank-wallet-ios/files/3146654/unstoppable_appicons.zip)

**Comment by ealymbaev** [comment]
Not renamed items:
- intro screen
- settings page app version
- about screen

**Comment by mNizhurin** [comment]
About icon updated. Need to update localized strings

**Comment by ealymbaev** [comment]
Localized titles should be renamed as well

**Comment by ealymbaev** [comment]
Tests are failing to run after renaming
