### ISSUE TITLE
Add new erc20 coin

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-ios#576]
- [x] USDT
contract address:  0xdAC17F958D2ee523a2206206994597C13D831ec7
- [x] @TalgatNurdinov please attach icon for this coin (for iOS)

**Comment by TalgatNurdinov** [comment]
https://github.com/horizontalsystems/HS-Design/blob/master/icons/coin_icons_ios/usdt.png
