### ISSUE TITLE
 Settings : finish security settings section

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-ios#59]
Release version will have:

- [x] implement cells as on design mockups
- [ ] The "import wallet" setting.  clicking on it would show user a confirmation dialog in bottom sheet controller similar to the confirmation dialog shown after the secret key backup. ** (1)This action will remove the currently installed wallet. (2)Backup its secret keys if you want too be able to access that wallet in the future. ""
- [x] clicking on "unlink from this device" would show user same alert as for "import wallet"

Below

<img width="509" alt="screen shot 2018-09-26 at 5 43 02 pm" src="https://user-images.githubusercontent.com/42367908/46077713-abc63300-c1b3-11e8-86d0-208f4ae629f3.png">

<img width="246" alt="screen shot 2018-09-26 at 5 42 24 pm" src="https://user-images.githubusercontent.com/42367908/46077679-92bd8200-c1b3-11e8-98c0-a0a0bbc7f4e3.png">

<img width="517" alt="screen shot 2018-09-21 at 3 18 46 pm" src="https://user-images.githubusercontent.com/42367908/45872761-9a93b580-bdb2-11e8-8977-20eba994ae57.png">

zpl://project?pid=5b167c731d079e4122e946b7&seid=5b8fa6c89ac5420ef6557cbe

**Comment by mNizhurin** [comment]
When switching touch id, request pin to set in case it was not done earlier.
