### ISSUE TITLE
Receive controller changes

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-ios#64]
- aligned to left new title
- in adress use 10...10 characters (if address less than 20 characters show full address. this will be the case with EOS blockchain and perhaps many other in the future)
- remove copy button (make copy instead share button)
- add share icon
![receive](https://user-images.githubusercontent.com/42367908/45478434-bf11e100-b765-11e8-9d91-3f8a4ee43748.png)

zpl://screen?sid=5b8fb90de311c97f95cd8518&pid=5b167c731d079e4122e946b7

**Comment by esengulov** [comment]
@TalgatNurdinov we need default share icon somewhere. I recommend using standard share icons (iOS/android) and place it to the right of the QR code
