### ISSUE TITLE
Implement huds 

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-ios#87]
- [ ] apply new hoods

Huds (light and dark modes)

- incorrect filling of fields
- incorrect pin
- copy 
- success after done

<img width="1172" alt="screen shot 2018-09-18 at 6 02 14 pm" src="https://user-images.githubusercontent.com/42367908/45686002-0258bf00-bb6d-11e8-860d-c365a9b42217.png">

zpl://screen?sid=5b5adcec8e733e2230fdc614&pid=5b167c731d079e4122e946b7

**Comment by esengulov** [comment]
@mNizhurin for success checkmark show the hud without "text".

**Comment by TalgatNurdinov** [comment]
Add second line for text

**Comment by Dianaaiym** [comment]
When there is no internet show a hud alert 
Use this key for alert ""
